rm galaxy from ecosystem
ansible/ecosystem-documentation pull request #15
Opened 2023-11-29 16:27 UTC by oraNod

Drop old galaxy link

2023-12-01 12:10 UTC, Andersson007 approved these changes

2023-12-07 21:30 UTC, samccann commented on templates/ecosystem.html
>              "description": "Galaxy NG jumpstarts automation projects with Ansible community content.",
FWIW - Galaxy just removed 'ng' from the website so maybe as part of this PR we can also just call it Galaxy here?

2023-12-08 11:14 UTC, Andersson007 commented on templates/ecosystem.html
>              "description": "Galaxy NG jumpstarts automation projects with Ansible community content.",
FWIW yeah, Galaxy NG stands for new generation AFAIK which is a dangerous type of name:)

2023-12-12 13:37 UTC, ssbarnea requested changes
Instead of removing, I would suggest replacing with current URL, which is https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/community/userguide/

2023-12-12 18:16 UTC, oraNod commented on templates/ecosystem.html
>              "description": "Galaxy NG jumpstarts automation projects with Ansible community content.",
I'm guessing from your comment in https://github.com/ansible/ecosystem-documentation/issues/23#issue-2038235310 that we continue to call this "Galaxy NG" - no change needed

2023-12-12 18:16 UTC, merged